"""empty message

Revision ID: 0a4259546036
Revises: 4140ba72f9c8
Create Date: 2022-06-03 21:13:55.900756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4259546036'
down_revision = '4140ba72f9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('padrao', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_roles_padrao'), 'roles', ['padrao'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_padrao'), table_name='roles')
    op.drop_column('roles', 'padrao')
    # ### end Alembic commands ###
