"""empty message

Revision ID: 252614b12274
Revises: 87de9af6e58b
Create Date: 2022-07-03 12:02:13.217834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252614b12274'
down_revision = '87de9af6e58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bandeira', sa.String(length=16), nullable=True),
    sa.Column('numero', sa.String(length=64), nullable=True),
    sa.Column('cvc', sa.String(length=4), nullable=True),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('limite', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartoes')
    # ### end Alembic commands ###
