"""empty message

Revision ID: 87de9af6e58b
Revises: f0ae32375d04
Create Date: 2022-06-24 19:30:08.943748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87de9af6e58b'
down_revision = 'f0ae32375d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas', sa.Column('enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas', 'enabled')
    # ### end Alembic commands ###
