"""empty message

Revision ID: a71112cb1e86
Revises: 0ec3d23bdb77
Create Date: 2022-05-27 21:55:40.928262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a71112cb1e86'
down_revision = '0ec3d23bdb77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('senha_hash', sa.String(length=128), nullable=False))
    op.drop_column('users', 'senha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('senha', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('users', 'senha_hash')
    # ### end Alembic commands ###
