"""empty message

Revision ID: f0ae32375d04
Revises: 0a4259546036
Create Date: 2022-06-24 18:45:59.761764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ae32375d04'
down_revision = '0a4259546036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('titular_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['titular_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contas')
    # ### end Alembic commands ###
